"""
Reports Page - generate and download Excel, CSV, ZIP, and PDF reports.

PERMANENT FIX (see project notes): download buttons used to live inside
`if st.button("Generate"):`. Streamlit's st.button() is only True on the
exact rerun right after it's clicked; downloading itself triggers another
rerun, at which point that condition is False again and the button +
bytes it needed vanish — this is what caused the "click Download -> stuck
loading -> blank screen" bug. The fix: persist generated bytes in
st.session_state so the download button is rendered from persisted state
on every rerun, not from a one-shot condition.

Also: raw tables with 100k+ rows are exported as CSV/ZIP, not Excel.
Writing that many rows via openpyxl measured at 80+ seconds for just three
sheets — CSV is ~80x faster for the same data and is the appropriate
format for flat transactional data anyway.
"""
import streamlit as st
import pandas as pd
from datetime import datetime
from utils import ui
from utils.data_handler import (
    get_merged_orders, CORE_FILES, get_cached_segments, get_cached_rfm11, get_cached_sentiment,
    get_cached_value_tiers, get_cached_inventory_forecast, get_cached_vendor_performance,
)
from utils.report_generator import build_excel_report, build_pdf_report, build_zip_report
from utils.ml_engine import compute_health_score, forecast_next_month_sales, compute_inventory_turnover

# Row count above which a table should never be embedded in an Excel sheet.
_EXCEL_ROW_LIMIT = 20_000


def _generate_and_offer_download(session_key, button_label, generate_fn, file_name, mime, help_text=None):
    """
    Renders a "Generate" button. On click, runs generate_fn() inside a
    try/except and spinner, and stores the resulting bytes in
    st.session_state[session_key]. The download button is then rendered
    from that persisted state on EVERY rerun (not only the rerun right
    after Generate was clicked) — this is what keeps it from vanishing
    when the download click itself triggers a rerun.
    """
    if st.button(button_label, width="stretch", key=f"{session_key}_btn", help=help_text):
        try:
            with st.spinner("Generating report..."):
                report_bytes = generate_fn()
            if report_bytes is None:
                st.warning("Nothing to export yet — there isn't enough data for this report.")
            else:
                st.session_state[session_key] = {
                    "bytes": report_bytes,
                    "file_name": file_name,
                    "mime": mime,
                    "generated_at": datetime.now(),
                }
        except Exception as e:
            # Permanent fix for "hidden errors -> white screen": surface the
            # failure as a normal message instead of letting it crash the run.
            st.error(f"Couldn't generate this report: {e}")

    persisted = st.session_state.get(session_key)
    if persisted:
        age = (datetime.now() - persisted["generated_at"]).seconds
        st.download_button(
            f"⬇️ Download ({persisted['file_name']})",
            persisted["bytes"],
            file_name=persisted["file_name"],
            mime=persisted["mime"],
            width="stretch",
            key=f"{session_key}_dl",
            help=f"Generated {age}s ago — click Generate again to refresh." if age > 5 else None,
        )


def render(data, user):
    ui.page_header("📄 Reports", "HOME &nbsp;›&nbsp; REPORTS")

    st.markdown("""
    <div style='background:linear-gradient(135deg, #161029 0%, #5b6ee1 100%);
                padding:18px 20px; border-radius:12px; color:white; margin-bottom:20px;'>
        <div style='font-size:14px; font-weight:700;'>📤 Export-ready business intelligence</div>
        <div style='font-size:12px; color:rgba(255,255,255,0.85); margin-top:6px;'>
            Every dataset, customer segment, and AI insight on this platform — packaged into
            Excel, PDF, CSV, or ZIP in one click, ready to share with stakeholders.
        </div>
    </div>
    """, unsafe_allow_html=True)

    try:
        merged = get_merged_orders(data)
    except Exception as e:
        st.error(f"Couldn't prepare report data: {e}")
        return

    customers = data.get("customers", pd.DataFrame())
    products = data.get("products", pd.DataFrame())
    feedback = data.get("feedback", pd.DataFrame())

    total_sales = merged["TotalAmount"].sum() if not merged.empty else 0
    total_orders = merged["OrderID"].nunique() if not merged.empty else 0
    total_customers = len(customers)
    avg_order = merged["TotalAmount"].mean() if not merged.empty else 0

    kpis = {
        "Total Sales": f"Rs. {total_sales:,.0f}",
        "Total Orders": f"{total_orders:,}",
        "Total Customers": f"{total_customers:,}",
        "Average Order Value": f"Rs. {avg_order:,.0f}",
        "Report Generated": datetime.now().strftime("%d %b %Y, %I:%M %p"),
    }

    # ---------------- Snapshot KPI strip ----------------
    k1, k2, k3, k4 = st.columns(4)
    with k1:
        ui.kpi_card("Total Sales", f"₹{total_sales:,.0f}", "all time", "💰", "#00c2d1")
    with k2:
        ui.kpi_card("Total Orders", f"{total_orders:,}", "all time", "🧾", "#5b6ee1")
    with k3:
        ui.kpi_card("Total Customers", f"{total_customers:,}", "in dataset", "👥", "#161029")
    with k4:
        ui.kpi_card("Avg Order Value", f"₹{avg_order:,.0f}", "per order", "📱", "#6c5ce7")

    st.markdown("<div style='height:22px;'></div>", unsafe_allow_html=True)

    # ---------------- Full "everything" report — ZIP of CSVs, not Excel ----------------
    ui.card_open("📦 Download Everything — Full Business Report", accent="#5b6ee1")
    st.markdown("Every core dataset plus AI analysis (customer segments, review sentiment, KPI summary, "
                "and a **Top vs Low value customer split** so you can see their impact on sales) "
                "— packaged as a **ZIP of CSVs** so it stays fast even at 100k+ rows per table.")

    tiered_rfm, tier_stats = (pd.DataFrame(), {})
    if not merged.empty:
        tiered_rfm, tier_stats = get_cached_value_tiers(merged)

    if tier_stats:
        top_s, low_s = tier_stats.get("Top", {}), tier_stats.get("Low", {})
        st.caption(
            f"📈 Top 20% of customers ({top_s.get('count', 0):,}) drive **{top_s.get('revenue_pct', 0)}%** "
            f"of revenue · Bottom 20% ({low_s.get('count', 0):,}) drive only **{low_s.get('revenue_pct', 0)}%**"
        )

    def _build_full_zip():
        sheets = {"kpi_summary": pd.DataFrame(list(kpis.items()), columns=["Metric", "Value"])}
        for key in CORE_FILES.keys():
            sheets[key] = data.get(key, pd.DataFrame())
        if not merged.empty:
            sheets["customer_segments"] = get_cached_segments(merged)
        if not feedback.empty:
            sheets["feedback_with_sentiment"] = get_cached_sentiment(feedback)
        if not tiered_rfm.empty:
            name_lookup = customers.set_index("CustomerID")["Name"] if "Name" in customers.columns else pd.Series(dtype=str)
            tagged = tiered_rfm.copy()
            tagged["Name"] = tagged["CustomerID"].map(name_lookup).fillna("—")
            cols = ["CustomerID", "Name", "Segment", "ValueTier", "Recency", "Frequency", "Monetary"]
            sheets["top_customers"] = tagged[tagged["ValueTier"] == "Top"][cols].sort_values("Monetary", ascending=False)
            sheets["low_customers"] = tagged[tagged["ValueTier"] == "Low"][cols].sort_values("Monetary")
            if tier_stats:
                sheets["top_vs_low_impact"] = pd.DataFrame([
                    {"Tier": t, "Customers": s["count"], "Revenue": s["revenue"],
                     "Revenue %": s["revenue_pct"], "Avg Spend": round(s["avg_spend"], 2)}
                    for t, s in tier_stats.items()
                ])
        return build_zip_report(sheets)

    _generate_and_offer_download(
        "full_report", "📦  Generate Full Report (ZIP)", _build_full_zip,
        f"CustomerLens_Full_Report_{datetime.now().strftime('%Y%m%d_%H%M')}.zip", "application/zip",
    )
    ui.card_close()

    st.markdown("<div style='height:18px;'></div>", unsafe_allow_html=True)

    # ---------------- Customer Segments / Action Center report ----------------
    ui.card_open("🎯 Customer Segments & Action Center Report", accent="#00c2d1")
    st.markdown("Export the full **11-tier RFM segmentation** with health scores — ready to hand to a "
                "retention or marketing team, in Excel or PDF.")

    rfm11 = pd.DataFrame()
    if not merged.empty:
        try:
            rfm11, tier_stats2 = get_cached_value_tiers(merged)
        except Exception as e:
            st.error(f"Couldn't compute segments: {e}")
            rfm11, tier_stats2 = pd.DataFrame(), {}
        if not rfm11.empty:
            name_lookup = customers.set_index("CustomerID")["Name"] if "Name" in customers.columns else pd.Series(dtype=str)
            rfm11["Name"] = rfm11["CustomerID"].map(name_lookup).fillna("—")
            rfm11["HealthScore"] = rfm11.apply(
                lambda r: compute_health_score(r["Recency"], r["Frequency"], r["Monetary"]), axis=1
            )
            rfm11 = rfm11[["CustomerID", "Name", "Segment", "ValueTier", "Recency", "Frequency", "Monetary", "HealthScore"]]

            seg_counts = rfm11["Segment"].value_counts()
            chip_html = "".join(
                f'<span style="background:#f5f7fb; border:1px solid #e9ecf5; color:#161029; '
                f'font-size:11px; font-weight:700; padding:4px 10px; border-radius:20px; margin:3px;">'
                f'{seg}: {cnt}</span>'
                for seg, cnt in seg_counts.items()
            )
            st.markdown(f"<div style='margin:10px 0;'>{chip_html}</div>", unsafe_allow_html=True)

    st.markdown("<div style='height:6px;'></div>", unsafe_allow_html=True)
    colX, colY = st.columns(2)

    with colX:
        def _build_segment_excel():
            if rfm11.empty:
                return None
            return build_excel_report({
                "All Customers (RFM)": rfm11,
                "Top Value Customers": rfm11[rfm11["ValueTier"] == "Top"].sort_values("Monetary", ascending=False),
                "Low Value Customers": rfm11[rfm11["ValueTier"] == "Low"].sort_values("Monetary"),
                "High Risk": rfm11[rfm11["Segment"].isin(["At Risk", "Lost Customers"])],
                "Champions": rfm11[rfm11["Segment"] == "Champions"],
                "Premium-Ready": rfm11[rfm11["Segment"].isin(["Loyal Customers", "Potential Loyalists"])],
            })
        # RFM table is one row per customer (not per order) so even at 100k+
        # customers this is a reasonably sized Excel sheet — safe to keep as .xlsx.
        _generate_and_offer_download(
            "segment_excel", "📗  Generate Segment Report (Excel)", _build_segment_excel,
            f"CustomerLens_Segments_{datetime.now().strftime('%Y%m%d_%H%M')}.xlsx",
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )


    with colY:
        def _build_segment_pdf():
            if rfm11.empty:
                return None
            high_risk_tbl = rfm11[rfm11["Segment"].isin(["At Risk", "Lost Customers"])].sort_values("Monetary", ascending=False).head(15)
            champions_tbl = rfm11[rfm11["Segment"] == "Champions"].sort_values("Monetary", ascending=False).head(15)
            return build_pdf_report(
                kpis,
                {"High Risk Customers (Top 15 by Spend)": high_risk_tbl, "Champions (Top 15 by Spend)": champions_tbl},
            )
        _generate_and_offer_download(
            "segment_pdf", "📕  Generate Segment Report (PDF)", _build_segment_pdf,
            f"CustomerLens_Segments_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf", "application/pdf",
        )
    ui.card_close()

    st.markdown("<div style='height:18px;'></div>", unsafe_allow_html=True)

    # ---------------- Focused / lightweight exports ----------------
    ui.card_open("📊 Business Summary Report", accent="#6c5ce7")
    st.markdown("A lighter, focused export: a small Excel workbook (summarized, not raw transactional "
                "rows), a formatted PDF executive summary, or the full raw order-level CSV.")
    st.markdown("<div style='height:8px;'></div>", unsafe_allow_html=True)

    colA, colB, colC = st.columns(3)

    with colA:
        st.markdown("""
        <div style='background:#f5f7fb; border-radius:10px; padding:14px; text-align:center; margin-bottom:10px;'>
            <div style='font-size:26px;'>📗</div>
            <div style='font-weight:800; color:#161029; font-size:13.5px; margin-top:4px;'>Excel Report</div>
            <div style='font-size:11px; color:#8b8fb3; margin-top:2px;'>Customers · Monthly Sales · Products · Feedback</div>
        </div>
        """, unsafe_allow_html=True)

        def _build_biz_excel():
            # Orders is summarized to monthly totals here, not dumped as raw
            # rows — a "business summary" workbook should stay small and
            # fast regardless of how many transactions exist. The complete
            # raw data is available via the CSV/ZIP exports instead.
            monthly_sales = pd.DataFrame()
            if not merged.empty and "Date" in merged.columns:
                monthly = merged.copy()
                monthly["Month"] = pd.to_datetime(monthly["Date"], errors="coerce").dt.to_period("M").astype(str)
                monthly_sales = monthly.groupby("Month").agg(
                    Orders=("OrderID", "nunique"), Revenue=("TotalAmount", "sum")
                ).reset_index()
            customers_sample = customers.head(_EXCEL_ROW_LIMIT)
            feedback_sample = feedback.head(_EXCEL_ROW_LIMIT)
            return build_excel_report({
                "Customers": customers_sample,
                "Monthly Sales Summary": monthly_sales,
                "Products": products,
                "Feedback (sample)": feedback_sample,
            })

        _generate_and_offer_download(
            "biz_excel", "Generate Excel Report", _build_biz_excel,
            f"CustomerLens_Report_{datetime.now().strftime('%Y%m%d_%H%M')}.xlsx",
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            help_text="Summarized workbook — for the complete raw dataset use the CSV export.",
        )

    with colB:
        st.markdown("""
        <div style='background:#f5f7fb; border-radius:10px; padding:14px; text-align:center; margin-bottom:10px;'>
            <div style='font-size:26px;'>📕</div>
            <div style='font-weight:800; color:#161029; font-size:13.5px; margin-top:4px;'>PDF Executive Summary</div>
            <div style='font-size:11px; color:#8b8fb3; margin-top:2px;'>KPIs + top customers + top products</div>
        </div>
        """, unsafe_allow_html=True)

        def _build_biz_pdf():
            top_customers = pd.DataFrame()
            top_products = pd.DataFrame()
            if not merged.empty:
                top_customers = merged.groupby(["CustomerID", "Name"])["TotalAmount"].sum().reset_index() \
                    .sort_values("TotalAmount", ascending=False).head(10)
                top_customers.columns = ["Customer ID", "Name", "Total Spend"]
                top_products = merged.groupby(["ProductID", "ProductName"])["Quantity"].sum().reset_index() \
                    .sort_values("Quantity", ascending=False).head(10)
                top_products.columns = ["Product ID", "Product Name", "Units Sold"]
            return build_pdf_report(
                kpis,
                {"Top 10 Customers by Spend": top_customers, "Top 10 Best-Selling Products": top_products},
            )

        _generate_and_offer_download(
            "biz_pdf", "Generate PDF Report", _build_biz_pdf,
            f"CustomerLens_Report_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf", "application/pdf",
        )

    with colC:
        st.markdown("""
        <div style='background:#f5f7fb; border-radius:10px; padding:14px; text-align:center; margin-bottom:10px;'>
            <div style='font-size:26px;'>📄</div>
            <div style='font-weight:800; color:#161029; font-size:13.5px; margin-top:4px;'>Raw CSV Export</div>
            <div style='font-size:11px; color:#8b8fb3; margin-top:2px;'>Complete merged order-level dataset</div>
        </div>
        """, unsafe_allow_html=True)

        def _build_orders_csv():
            if merged.empty:
                return None
            return merged.to_csv(index=False).encode("utf-8")

        _generate_and_offer_download(
            "biz_csv", "Generate CSV Export", _build_orders_csv,
            f"CustomerLens_Orders_{datetime.now().strftime('%Y%m%d_%H%M')}.csv", "text/csv",
        )

    ui.card_close()

    st.markdown("<div style='height:18px;'></div>", unsafe_allow_html=True)

    # ---------------- Retail business reports: Product / Inventory / Forecast / AI Insight ----------------
    is_vendor = user["role"] == "Vendor"
    ui.card_open("🏬 Retail Business Reports", accent="#161029")
    st.markdown("Product, inventory, demand-forecast, and AI-insight reports" +
                (" scoped to your own brand." if is_vendor else " across the full catalog.") +
                " Each is available as Excel, PDF, or CSV.")
    st.markdown("<div style='height:8px;'></div>", unsafe_allow_html=True)

    rep_tab1, rep_tab2, rep_tab3, rep_tab4 = st.tabs([
        "📦 Product Report", "🏭 Inventory Report", "📈 Forecast Report", "🤖 AI Insight Report",
    ])

    # ---- Product Report ----
    with rep_tab1:
        if products.empty:
            st.info("No product data available.")
        else:
            colP1, colP2 = st.columns(2)
            with colP1:
                def _build_product_excel():
                    top_selling = pd.DataFrame()
                    if not merged.empty:
                        top_selling = merged.groupby(["ProductID", "ProductName"])["Quantity"].sum() \
                            .reset_index().sort_values("Quantity", ascending=False)
                    return build_excel_report({
                        "Products": products,
                        "Top Selling": top_selling,
                        "Low Stock (<20)": products[products["Stock"] < 20] if "Stock" in products.columns else pd.DataFrame(),
                    })
                _generate_and_offer_download(
                    "product_excel", "📗 Generate Product Report (Excel)", _build_product_excel,
                    f"CustomerLens_Products_{datetime.now().strftime('%Y%m%d_%H%M')}.xlsx",
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                )
            with colP2:
                def _build_product_pdf():
                    top_selling = pd.DataFrame()
                    if not merged.empty:
                        top_selling = merged.groupby(["ProductID", "ProductName"])["Quantity"].sum() \
                            .reset_index().sort_values("Quantity", ascending=False).head(15)
                        top_selling.columns = ["Product ID", "Product Name", "Units Sold"]
                    low_stock = products[products["Stock"] < 20].head(15) if "Stock" in products.columns else pd.DataFrame()
                    return build_pdf_report(kpis, {"Top 15 Best Sellers": top_selling, "Low Stock Products": low_stock})
                _generate_and_offer_download(
                    "product_pdf", "📕 Generate Product Report (PDF)", _build_product_pdf,
                    f"CustomerLens_Products_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf", "application/pdf",
                )
            st.download_button(
                "⬇️ Raw Products CSV", products.to_csv(index=False).encode("utf-8"),
                file_name=f"CustomerLens_Products_{datetime.now().strftime('%Y%m%d_%H%M')}.csv",
                mime="text/csv", width="stretch", key="product_csv_dl",
            )

    # ---- Inventory Report ----
    with rep_tab2:
        inventory = data.get("inventory", pd.DataFrame())
        turnover = compute_inventory_turnover(merged, products) if not merged.empty else pd.DataFrame()
        if products.empty:
            st.info("No inventory data available.")
        else:
            colI1, colI2 = st.columns(2)
            with colI1:
                def _build_inventory_excel():
                    sheets = {
                        "Stock Levels": products[[c for c in ["ProductID", "ProductName", "Category", "Brand", "Stock"] if c in products.columns]],
                        "Low / Out of Stock": products[products["Stock"] < 20] if "Stock" in products.columns else pd.DataFrame(),
                        "Turnover": turnover,
                    }
                    if not inventory.empty:
                        sheets["Store Inventory"] = inventory
                    return build_excel_report(sheets)
                _generate_and_offer_download(
                    "inventory_excel", "📗 Generate Inventory Report (Excel)", _build_inventory_excel,
                    f"CustomerLens_Inventory_{datetime.now().strftime('%Y%m%d_%H%M')}.xlsx",
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                )
            with colI2:
                def _build_inventory_pdf():
                    low_stock = products[products["Stock"] < 20].head(15) if "Stock" in products.columns else pd.DataFrame()
                    turnover_tbl = turnover.head(15) if not turnover.empty else pd.DataFrame()
                    return build_pdf_report(kpis, {"Low / Out-of-Stock Products": low_stock, "Top Turnover Products": turnover_tbl})
                _generate_and_offer_download(
                    "inventory_pdf", "📕 Generate Inventory Report (PDF)", _build_inventory_pdf,
                    f"CustomerLens_Inventory_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf", "application/pdf",
                )

    # ---- Forecast Report ----
    with rep_tab3:
        if merged.empty:
            st.info("No order history available to forecast from.")
        else:
            _, sales_forecast = forecast_next_month_sales(merged, months_ahead=3)
            inv_forecast = get_cached_inventory_forecast(merged, products, data.get("inventory", pd.DataFrame()), months_ahead=1)
            colF1, colF2 = st.columns(2)
            with colF1:
                def _build_forecast_excel():
                    return build_excel_report({
                        "Sales Forecast (3mo)": sales_forecast,
                        "Inventory Demand Forecast": inv_forecast,
                    })
                _generate_and_offer_download(
                    "forecast_excel", "📗 Generate Forecast Report (Excel)", _build_forecast_excel,
                    f"CustomerLens_Forecast_{datetime.now().strftime('%Y%m%d_%H%M')}.xlsx",
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                )
            with colF2:
                def _build_forecast_pdf():
                    sf = sales_forecast.rename(columns={"TotalAmount": "Forecasted Revenue (Rs.)"}) if not sales_forecast.empty else sales_forecast
                    inf = inv_forecast.head(15)[["ProductName", "PredictedDemand", "RecommendedReorderQty", "RiskLevel"]] if not inv_forecast.empty else pd.DataFrame()
                    return build_pdf_report(kpis, {"3-Month Sales Forecast": sf, "Top 15 Products by Predicted Demand": inf})
                _generate_and_offer_download(
                    "forecast_pdf", "📕 Generate Forecast Report (PDF)", _build_forecast_pdf,
                    f"CustomerLens_Forecast_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf", "application/pdf",
                )

    # ---- AI Insight Report ----
    with rep_tab4:
        st.caption("Bundles segmentation, churn-risk exposure, and (for Admins) vendor performance ranking into one export.")
        rfm_ai, _ = get_cached_value_tiers(merged) if not merged.empty else (pd.DataFrame(), {})
        feedback = data.get("feedback", pd.DataFrame())
        colA1, colA2 = st.columns(2)
        with colA1:
            def _build_ai_excel():
                sheets = {}
                if not rfm_ai.empty:
                    sheets["Customer Segments"] = rfm_ai
                    sheets["At Risk / Lost"] = rfm_ai[rfm_ai["Segment"].isin(["At Risk", "Lost Customers"])] if "Segment" in rfm_ai.columns else pd.DataFrame()
                if not is_vendor and not merged.empty:
                    vperf = get_cached_vendor_performance(merged, feedback)
                    if not vperf.empty:
                        sheets["Vendor Performance"] = vperf
                if not sheets:
                    return None
                return build_excel_report(sheets)
            _generate_and_offer_download(
                "ai_excel", "📗 Generate AI Insight Report (Excel)", _build_ai_excel,
                f"CustomerLens_Insights_{datetime.now().strftime('%Y%m%d_%H%M')}.xlsx",
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            )
        with colA2:
            def _build_ai_pdf():
                tables = {}
                if not rfm_ai.empty and "Segment" in rfm_ai.columns:
                    tables["At-Risk / Lost Customers (Top 15)"] = rfm_ai[rfm_ai["Segment"].isin(
                        ["At Risk", "Lost Customers"])].sort_values("Monetary", ascending=False).head(15)
                if not is_vendor and not merged.empty:
                    vperf = get_cached_vendor_performance(merged, feedback)
                    if not vperf.empty:
                        tables["Vendor Performance Ranking (Top 15)"] = vperf.head(15)
                if not tables:
                    return None
                return build_pdf_report(kpis, tables)
            _generate_and_offer_download(
                "ai_pdf", "📕 Generate AI Insight Report (PDF)", _build_ai_pdf,
                f"CustomerLens_Insights_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf", "application/pdf",
            )

    ui.card_close()
